#include <string>
#include <vector>

using namespace std;

#define STRT 1
#define EXTERNAL_DECLARATION 2
#define EXTERNAL_NON_STRUCT_LR 3
#define EXTERNAL_STRUCT_LR1 4
#define EXTERNAL_STRUCT_LR2 5
#define STMT_LIST 6
#define STMT 7
#define STRUCT_STMT 8
#define STRUCT_STMT_LR 9
#define COMPOUND_STMTS 10
#define COMPOUND_STMTS_E 11
#define OPTIONAL_COMPOUND_STMT 12
#define DECLARATION_LIST 13
#define OPTIONAL_DECL_EXT 14
#define DECLARATION 15
#define DECLARATION_NON_STRUCT 16
#define DECLARATION_STRUCT 17
#define ASSIGNED_IDENTIFIER_LIST 18
#define OPTIONAL_ASSIGNED_IDENTIFIER_LIST_EXT 19
#define IDENTIFIER_LIST 20
#define IDENTIFIER_LIST_E 21
#define OPTIONAL_IDENTIFIER_LIST_EXT 22
#define ASSIGNED_IDENTIFIER 23
#define OPTIONAL_ASSIGNMENT 24
#define ARG_LIST 25
#define OPTIONAL_ARG_LIST_EXTENSION 26
#define PARAM_LIST 27
#define OPTIONAL_PARAM_EXTENSION 28
#define CONDITIONAL_STMT 29
#define OPTIONAL_ELSE 30
#define ITERATION_STMT 31
#define JUMP_STMT 32
#define OPTIONAL_EXPR 33
#define EXPR 34
#define EXPR_E 35
#define EXPR_LR1 36
#define EXPR_LR2 37
#define IDENTIFIER 38
#define IDENTIFIER_E 39
#define ID_LR 40
#define BR_DIMLIST1 41
#define BR_DIMLIST_LR 42
#define OPERATOR 43
#define ASSIGNMENT_OP 44
#define RELATIONAL_OP 45
#define LOGICAL_OP 46
#define BINARY_OP 47
#define SEMI 48
#define DATA_TYPE_NON_STRUCT 49
#define DATA_TYPE_NON_STRUCT_E 50
#define ID 51
#define NUMBER 52
#define LEFT_PARENTHESIS 53
#define LEFT_PARENTHESIS_E 54
#define RIGHT_PARENTHESIS 55
#define LEFT_BRACE 56
#define LEFT_BRACE_E 57
#define RIGHT_BRACE 58
#define LEFT_BRACKET 59
#define RIGHT_BRACKET 60

vector<string> codeToString = {
    "STRT",
    "EXTERNAL_DECLARATION",
    "EXTERNAL_NON_STRUCT_LR",
    "EXTERNAL_STRUCT_LR1",
    "EXTERNAL_STRUCT_LR2",
    "STMT_LIST",
    "STMT",
    "STRUCT_STMT",
    "STRUCT_STMT_LR",
    "COMPOUND_STMTS",
    "COMPOUND_STMTS_E",
    "OPTIONAL_COMPOUND_STMT",
    "DECLARATION_LIST",
    "OPTIONAL_DECL_EXT",
    "DECLARATION",
    "DECLARATION_NON_STRUCT",
    "DECLARATION_STRUCT",
    "ASSIGNED_IDENTIFIER_LIST",
    "OPTIONAL_ASSIGNED_IDENTIFIER_LIST_EXT",
    "IDENTIFIER_LIST",
    "IDENTIFIER_LIST_E",
    "OPTIONAL_IDENTIFIER_LIST_EXT",
    "ASSIGNED_IDENTIFIER",
    "OPTIONAL_ASSIGNMENT",
    "ARG_LIST",
    "OPTIONAL_ARG_LIST_EXTENSION",
    "PARAM_LIST",
    "OPTIONAL_PARAM_EXTENSION",
    "CONDITIONAL_STMT",
    "OPTIONAL_ELSE",
    "ITERATION_STMT",
    "JUMP_STMT",
    "OPTIONAL_EXPR",
    "EXPR",
    "EXPR_E",
    "EXPR_LR1",
    "EXPR_LR2",
    "IDENTIFIER",
    "IDENTIFIER_E",
    "ID_LR",
    "BR_DIMLIST1",
    "BR_DIMLIST_LR",
    "OPERATOR",
    "ASSIGNMENT_OP",
    "RELATIONAL_OP",
    "LOGICAL_OP",
    "BINARY_OP",
    "SEMI",
    "DATA_TYPE_NON_STRUCT",
    "DATA_TYPE_NON_STRUCT_E",
    "ID",
    "NUMBER",
    "LEFT_PARENTHESIS",
    "LEFT_PARENTHESIS_E",
    "RIGHT_PARENTHESIS",
    "LEFT_BRACE",
    "LEFT_BRACE_E",
    "RIGHT_BRACE",
    "LEFT_BRACKET",
    "RIGHT_BRACKET",
};